# Generated by Django 5.2.7 on 2025-10-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_contact_first_name_contact_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
